### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by wohuiaini008** [91Act/curl-unity#1]
EntryPointNotFoundException: curl_multi_init
CurlUnity.CurlMulti..ctor (System.IntPtr ptr) (at Assets/curl-unity/Scripts/CurlMulti.cs:38)
CurlTest.Start () (at Assets/curl-unity/CurlTest.cs:10)
您好 ，我在导入assets后直接运行，发现这个错误 ，检查了那个dll是存在的，是不是还有其他安装工作需要做 ？

**Comment by Jayatubi** [comment]
重新构建了Windows的dll，请更新之后再试。
