### ISSUE TITLE
请问怎么在下载进行中修改限速呢？直接设置SetOpt编辑器好用，安卓真机不好用

### ISSUE THREAD

**Issue by huiball** [91Act/curl-unity#10]
easy.SetOpt(CURLOPT.MAX_RECV_SPEED_LARGE, speed);

我是这么直接设置的，编辑器上速度会变，安卓真机上不管用

**Comment by Jayatubi** [comment]
关于这个选项的具体描述可以看看官方文档的介绍：https://curl.haxx.se/libcurl/c/CURLOPT_MAX_RECV_SPEED_LARGE.html
从文档上看这个选项似乎并不是直接限制了速度，而是限制的吞吐量，即在某个时刻的吞吐量超过了限制，curl会在后面通过暂停传输的方式来降低平均速度。

你也可以试试把这个curl的可执行文件直接推送给Android设备：https://github.com/91Act/curl-unity/blob/master/build/curl/prebuilt/android/armeabi-v7a/bin/curl
这个Androids设备可能需要root了之后才能执行自编译的可执行文件，然后使用curl的命令行方式来测试限速的效果。

如果还是有问题，你可能需要去curl的官方github提issue。

**Comment by huiball** [comment]
那我有办法在实际应用时控制下载写入的速度么，下载过快占用CPU过高，希望能限制一下

**Comment by huiball** [comment]
> 那我有办法在实际应用时控制下载写入的速度么，下载过快占用CPU过高，希望能限制一下

通过控制MutilUpdater的Busy Interval 可以吧

**Comment by Jayatubi** [comment]
那个参数就是用来做这个限制的。
