### ISSUE TITLE
CurlEasy.cs 里  ProgressFunction的参数类型是否应该是long？

### ISSUE THREAD

**Issue by huiball** [91Act/curl-unity#11]
int的话编辑器是好的，安卓真机是不对的，打的armv7的版本

**Comment by Jayatubi** [comment]
是否有具体的错误信息

**Comment by Jayatubi** [comment]
https://github.com/91Act/curl-unity/blob/3e628772416ac1084d93e670b9355776dfb9d0d4/build/curl/curl-7.67.0/include/curl/curl.h#L214

升级新版本之后函数签名变了，应该是double才对。你可以先试试，如果可以欢迎提交PR。

**Comment by Jayatubi** [comment]
https://github.com/91Act/curl-unity/blob/3e628772416ac1084d93e670b9355776dfb9d0d4/build/curl/curl-7.67.0/include/curl/curl.h#L223


emmm...上面那个回调已经被标记为过时了，应该用这个新版的回调，相应的opt参数也需要调整。不过旧版回调应该还能继续使用。

**Comment by Jayatubi** [comment]
https://github.com/91Act/curl-unity/blob/5c733b5f273adfe3caf7269c5a1601e4445c58ff/build/curl/curl-7.67.0/include/curl/system.h#L34


curl_off_t 原则上不论什么平台都应该对于64bit的数据，这里应该用long。

**Comment by Jayatubi** [comment]
Fixed in 435848e
