### ISSUE TITLE
关于使用CurlMulti多线程下载的问题

### ISSUE THREAD

**Issue by huiball** [91Act/curl-unity#12]
请问一下，我仿照例子，创建了3个CurlEasy，调用MultiPerform加入一个创建的CurlMulti，但是总是在第一个CurlEasy的GET执行完之后，后面的GET才会被发送，这个可能是什么原因？三个CurlEasy的HEAD都正确同时执行过了。

**Comment by Jayatubi** [comment]
能提供测试代码么？

**Comment by huiball** [comment]
不好意思，没事了，应该是我测试用的文件服务器可能有问题，我测试了外链没问题
