### ISSUE TITLE
CurlMulti可能会有多线程导致崩溃的问题？

### ISSUE THREAD

**Issue by huiball** [91Act/curl-unity#13]
使用多线程的CurlMultiUpdater下载过程中调用CurlMulti的Abort有几率会崩溃，堆栈如下：
0x00007FFF0B714699 (curl) curl_mvsprintf
0x00007FFF0B71B812 (curl) curl_multi_wait
0x00007FFF0B71A1D6 (curl) curl_multi_perform
0x00000000BF64A6B6 (curl) CurlUnity.Lib.curl_multi_perform()
0x00000000BF649DBB (curl) CurlUnity.CurlMulti.Perform()
0x0000000002768CC3 (curl) CurlUnity.CurlMultiUpdater.Perform()

怀疑是主线程逻辑调用的CurlMulti的RemoveEasy和分线程下载时调用的Perform有多线程问题，华谊是不是curl_multi_remove_handle和curl_multi_perform在两个线程跑没加锁会有问题？

我把CurlMulti的AddEasy、RemoveEasy、CleanUp和Perform加了代码段锁保护后好像没有重现了，大佬帮忙看下？谢谢啦

**Comment by Jayatubi** [comment]
能否提供可复现的工程。你提到的几个函数（除了CleanUp）都已经有锁，你是怎么改的呢？

**Comment by huiball** [comment]
> 能否提供可复现的工程。你提到的几个函数（除了CleanUp）都已经有锁，你是怎么改的呢？

目前只锁了workingEasies，但是Lib的操作好像也有多线程问题。

简单改了下例子里的ResumeDownload.cs，反复点几次开始暂停就能复现了。

[ResumeDownload.zip](https://github.com/91Act/curl-unity/files/4393228/ResumeDownload.zip)

**Comment by huiball** [comment]
另外还有一个问题，貌似CurlEasy在下载途中如果遇到中断连接之类的需要retry的情况，重新下载时没有考虑续传，而是从头请求了。这里最好能获取下当前已经完成的部分。OnMultiPerform那里

**Comment by huiball** [comment]
> 能否提供可复现的工程。你提到的几个函数（除了CleanUp）都已经有锁，你是怎么改的呢？

提了个pr，你看下我是这么改了下测试了下没啥问题了

**Comment by Jayatubi** [comment]
> 另外还有一个问题，貌似CurlEasy在下载途中如果遇到中断连接之类的需要retry的情况，重新下载时没有考虑续传，而是从头请求了。这里最好能获取下当前已经完成的部分。OnMultiPerform那里

续传属于上层应用逻辑，底层不做处理。Curl不只是用来做下载用的，更多的时候用来做HTTP API请求。

**Comment by huiball** [comment]
> > 另外还有一个问题，貌似CurlEasy在下载途中如果遇到中断连接之类的需要retry的情况，重新下载时没有考虑续传，而是从头请求了。这里最好能获取下当前已经完成的部分。OnMultiPerform那里
> 
> 续传属于上层应用逻辑，底层不做处理。Curl不只是用来做下载用的，更多的时候用来做HTTP API请求。

嗯好的，那个主要是在发生例如网络环境改变或者连接被中断重连时，CurlEasy没有提供一个回调给外面直接就进行重试了，因为下载请求涉及ContentRange，重复请求会导致下载内容有问题

**Comment by Jayatubi** [comment]
> > > 另外还有一个问题，貌似CurlEasy在下载途中如果遇到中断连接之类的需要retry的情况，重新下载时没有考虑续传，而是从头请求了。这里最好能获取下当前已经完成的部分。OnMultiPerform那里
> > 
> > 
> > 续传属于上层应用逻辑，底层不做处理。Curl不只是用来做下载用的，更多的时候用来做HTTP API请求。
> 
> 嗯好的，那个主要是在发生例如网络环境改变或者连接被中断重连时，CurlEasy没有提供一个回调给外面直接就进行重试了，因为下载请求涉及ContentRange，重复请求会导致下载内容有问题

如果是这种需求，你可以在上层应用的时候，将retrycount设置为0，curl会在第一次失败就通知上层。

**Comment by huiball** [comment]
好的，明白了！
