### ISSUE TITLE
PC端正常运行 ，android端运行异常

### ISSUE THREAD

**Issue by wohuiaini008** [91Act/curl-unity#2]
Failed to request: https://nghttp2.org/, reason: COULDNT_
[log.txt](https://github.com/91Act/curl-unity/files/3781992/log.txt)
RESOLVE_HOST

**Comment by Jayatubi** [comment]
`COULDNT_RESOLVE_HOST`是指你的设备无法完成DNS解析。请检查你的设备的网络和DNS服务器设置。你也可以换一个其他的url来测试。

如果你需要使用代理服务器，你可以试试：
```
easy.SetOpt(CurlUnity.CURLOPT.PROXY, "[scheme]://server:port");
```
[参考](https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html)

**Comment by wohuiaini008** [comment]
好像不是网络的问题，之前我提过 我在我的电脑上运行之前的版本可以运行 ，pc android都有返回 ，换个电脑运行报错提示dll找不到 或者&nbsp;
提示point .....什么找不到 忘记了 ，&nbsp; 之后您更新了版本， 我运行后另外一台电脑pc也能正常跑并且取到数据 ，&nbsp; 但是打包到android端 就提示COULDNT_RESOLVE_HOST的问题, 我试了我自己的电脑也是同样的问题 ， 刚刚我又试了现在的版本和之前的版本 ，确认如我描述这样 ，当前版本url 地址 使用了https://nghttp2.org&nbsp;和我们的 服务器地址 都是这样的 ，我在android端使用浏览器 链接https://nghttp2.org&nbsp;是可以进去的，麻烦看下什么原因


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jayatubi"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月29日(星期二) 下午3:18
收件人:&nbsp;"91Act/curl-unity"<curl-unity@noreply.github.com&gt;;
抄送:&nbsp;"一辉"<772142166@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [91Act/curl-unity] PC端正常运行 ，android端运行异常 (#2)




COULDNT_RESOLVE_HOST是指你的设备无法完成DNS解析。请检查你的设备的网络和DNS服务器设置。你也可以换一个其他的url来测试。

**Comment by Jayatubi** [comment]
你可以试试直接使用IP地址是否能正常链接：
```
; <<>> DiG 9.10.3-P4-Ubuntu <<>> nghttp2.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3020
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;nghttp2.org.                   IN      A

;; ANSWER SECTION:
nghttp2.org.            299     IN      A       139.162.123.134

;; Query time: 1007 msec
;; SERVER: 10.10.4.10#53(10.10.4.10)
;; WHEN: Tue Oct 29 15:50:15 CST 2019
;; MSG SIZE  rcvd: 56
```

**Comment by Jayatubi** [comment]
测试了，是Android权限的问题，在AndroidManifest.xml里面添加`<uses-permission android:name="android.permission.INTERNET" />`即可，稍后提供一个模板。

**Comment by Jayatubi** [comment]
Fixed in 900ebeba07019d7f352d9bde9b91049a613579e6
