### ISSUE TITLE
xcode build报错 

### ISSUE THREAD

**Issue by wohuiaini008** [91Act/curl-unity#3]
'/Users/username/Documents/projectdir/iOS/ProjectName/Libraries/curl-unity/Plugins/ios/libcurl.a(libcurl_la-easy.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

Xcode build失败 提示以上报错 ，好像可以通过关闭BitCode解决，后面这个第三方库会支持BitCode吗

**Comment by Jayatubi** [comment]
BitCode的构建依赖于所有用到第三方库都能支持BitCode构建，现在尚不确定能否实现，需要验证。如果你有好的修改方式欢迎PR。

**Comment by wohuiaini008** [comment]
好的 ，如果这个第三方库验证可以支持BitCode，或者后面更新了支持BitCode，麻烦告知

**Comment by wohuiaini008** [comment]
Use Xcode to build exported Unity-iPhone project, It will build failed by reason:

'/Users/username/Documents/projectdir/iOS/ProjectName/Libraries/curl-unity/Plugins/ios/libcurl.a(libcurl_la-easy.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

Then I turn off Bitcode, but It build failed by another reason:

![{93D2BC44-4A90-BBE9-D7FE-C40179907A82}](https://user-images.githubusercontent.com/30223216/67832429-99d46380-fb1c-11e9-94d6-5391a31d8520.JPG)

I have no idea how to solve this.

**Comment by Jayatubi** [comment]
最新提交的二进制已开启bitcode
