### ISSUE TITLE
Update curl to 7.64.1

### ISSUE THREAD

**Issue by y0n3t4n1** [91Act/curl-unity#4]
I'm experiencing a crash similar to what is described in curl/curl#3463, especially on iOS.  Apparently the fix has already made it into 7.64.1.

**Comment by Jayatubi** [comment]
Could you please provide the reporoducable steps to verify that?

**Comment by y0n3t4n1** [comment]
As mentioned in the issue above, build the crawler example linked against the included libcurl and run it until it crashed; note that it's an occasional crash, your mileage may vary:
```
cd build/curl
# you may need this if you're on macOS 10.14 or above
export PKG_CONFIG_SYSROOT_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
# change this according to your platform
included_curl=prebuilt/osx/lib/libcurl.dylib

gcc curl-7.64.0/docs/examples/crawler.c $included_curl \
    $(pkg-config --cflags --libs libxml-2.0) && ./a.out
```

**Comment by Jayatubi** [comment]
This repo aims to build a curl lib and the c# wrapper for unity, it doesn't care about the standardalone runtime applications. It would be great if you could tell how to reproduce the issue with unity engine. Anyway I might update the curl library to the latest stable as well.

**Comment by y0n3t4n1** [comment]
I fully understand what you mean, but as the project is not a personal one, so I need to extract the relevant part and the file list before disclosing it to you, hence the instruction above :)
Anyway, since this is an upstream bug in http2 handling code, it could happen to any product (including yours, maybe) using curl-7.64.0 if it's downloading a bunch of files using http2.

**Comment by Jayatubi** [comment]
The libcurl has been updated to 7.67.0 and the nghttp2 has been update to 1.39.2. You could try these new libs and please reopen this issue if this doesn't work for you.

**Comment by y0n3t4n1** [comment]
Thank you!

**Comment by y0n3t4n1** [comment]
Looks like the iOS plugin is built from the older version...
```
$ git grep -F 7.67.0 Assets
Binary file Assets/curl-unity/Plugins/android/arm64-v8a/libcurl.so matches
Binary file Assets/curl-unity/Plugins/android/armeabi-v7a/libcurl.so matches
Binary file Assets/curl-unity/Plugins/android/x86/libcurl.so matches
Binary file Assets/curl-unity/Plugins/osx/curl.bundle/Contents/MacOS/curl matches
Binary file Assets/curl-unity/Plugins/win/curl.dll matches
$ git grep -F 7.64.0 Assets
Binary file Assets/curl-unity/Plugins/ios/libcurl.a matches
```

**Comment by Jayatubi** [comment]
Thanks for the PR and the prebuilt libs were updated.
